name: Publish Docker image
on:
  push:
    branches: [ docker ]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-16.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: A5-015/ramen/ramen-sim
          tag_with_ref: true
          file: ./simulation/docker/Dockerfile


