name: test-suite
on: [push]
jobs:
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/a5-015/ramen/ramen-dev
  #   steps:  
  #     - uses: actions/checkout@v1
  #       with: 
  #         submodules: true
  #     - name: Prepare cmake
  #       working-directory: ./library
  #       run: cmake .
  #     - name: Build ramen and unit tests
  #       working-directory: ./library
  #       run: make ramen_unit_tests
  #     - name: Run the unit tests
  #       run: ./library/bin/ramen_unit_tests

  virtual-mesh-network:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/a5-015/ramen/ramen-dev
    steps:  
      - uses: actions/checkout@v1
        with: 
          submodules: true
      - name: Prepare cmake
        working-directory: ./library
        run: cmake .
      - name: Build ramen and virtual mesh network
        working-directory: ./library
        run: make virtual_esp
      - name: Run the virtual mesh network with 10 nodes for 5 seconds
        run: ./library/bin/virtual_esp -t 5 -n 10

  platformio-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/a5-015/ramen/ramen-dev
    steps:  
      - uses: actions/checkout@v2
      - name: Install ramen as a library with PlatformIO
        run: platformio lib --global install painlessMesh
      - name: Build basic.ino example with PlatformIO
        working-directory: ./library
        run: platformio ci --lib="." --board=nodemcuv2 examples/basic/basic.ino -O "build_flags = -Wall -Wextra -Wno-unused-parameter"